
// import Navbar from './components/Navbar'
// import Sidebar from './components/Sidebar'
import './globals.css'

export const metadata = {
  title: 'Follow-Up',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      {/* <Navbar/>
      <Sidebar/> */}
      </body>
    </html>
  )
}
